#!/bin/sh

workspaceIndex=$(i3-msg -t get_workspaces | tr , '\n' | grep '"num":' | cut -d : -f 2 | sort  | awk '$1!=NR{print NR;exit}')


# otherwise create new
if ! [ "$workspaceIndex" -ge 0 ] ;
then
        echo "No gap found"
        workspaceIndex=$(($(i3-msg -t get_workspaces | tr , '\n' | grep '"num":' | cut -d : -f 2 | sort -rn | head -1) + 1))
fi



i3-msg move window to workspace number $workspaceIndex
