#!/bin/sh

new_workspace=$(($(i3-msg -t get_workspaces | tr , '\n' | grep '"num":' | cut -d : -f 2 | sort -rn | head -1) + 1))
# active_workspace=$( i3-msg -t get_workspaces | jq '.[] | select(.focused).num' )

# toplevel_containers=$( i3-msg -t get_tree | jq '(.nodes[].nodes[].nodes[] | select(.type=="workspace") | select(.num=='"$active_workspace"') | .nodes | length) // 0' )


i3-msg move window to workspace number $new_workspace
